# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RoC.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(499, 424)
        self.stackedWidget = QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 481, 401))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(0, 170, 255);")
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.entrar = QPushButton(self.page_4)
        self.entrar.setObjectName(u"entrar")
        self.entrar.setGeometry(QRect(150, 280, 75, 23))
        self.contrasena = QLineEdit(self.page_4)
        self.contrasena.setObjectName(u"contrasena")
        self.contrasena.setGeometry(QRect(110, 240, 151, 21))
        self.contrasena.setEchoMode(QLineEdit.Password)
        self.usuario = QLabel(self.page_4)
        self.usuario.setObjectName(u"usuario")
        self.usuario.setGeometry(QRect(150, 100, 61, 41))
        font = QFont()
        font.setFamily(u"Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.usuario.setFont(font)
        self.usuario.setAlignment(Qt.AlignCenter)
        self.usuario_2 = QLineEdit(self.page_4)
        self.usuario_2.setObjectName(u"usuario_2")
        self.usuario_2.setGeometry(QRect(110, 140, 151, 31))
        self.usuario_2.setEchoMode(QLineEdit.Normal)
        self.contra = QLabel(self.page_4)
        self.contra.setObjectName(u"contra")
        self.contra.setGeometry(QRect(120, 200, 121, 31))
        self.contra.setFont(font)
        self.contra.setAlignment(Qt.AlignCenter)
        self.titulo = QLabel(self.page_4)
        self.titulo.setObjectName(u"titulo")
        self.titulo.setGeometry(QRect(160, 50, 61, 31))
        font1 = QFont()
        font1.setFamily(u"Consolas")
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setWeight(75)
        self.titulo.setFont(font1)
        self.stackedWidget.addWidget(self.page_4)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label = QLabel(self.page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 10, 131, 71))
        self.mover_r = QPushButton(self.page)
        self.mover_r.setObjectName(u"mover_r")
        self.mover_r.setGeometry(QRect(250, 260, 91, 31))
        self.herramienta = QPushButton(self.page)
        self.herramienta.setObjectName(u"herramienta")
        self.herramienta.setGeometry(QRect(70, 260, 91, 31))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_4 = QLabel(self.page_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 0, 311, 61))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"background-color: rgb(101, 117, 143);")
        self.nodo_E = QRadioButton(self.page_2)
        self.nodo_E.setObjectName(u"nodo_E")
        self.nodo_E.setGeometry(QRect(180, 110, 100, 40))
        font2 = QFont()
        font2.setFamily(u"Consolas")
        font2.setPointSize(10)
        self.nodo_E.setFont(font2)
        self.nodo_E.setStyleSheet(u"background-color: rgb(79, 95, 111);")
        self.nodo_G = QRadioButton(self.page_2)
        self.nodo_G.setObjectName(u"nodo_G")
        self.nodo_G.setGeometry(QRect(180, 160, 100, 40))
        self.nodo_G.setFont(font2)
        self.nodo_G.setStyleSheet(u"background-color: rgb(79, 95, 111);")
        self.nodo_B = QRadioButton(self.page_2)
        self.nodo_B.setObjectName(u"nodo_B")
        self.nodo_B.setGeometry(QRect(180, 60, 100, 40))
        self.nodo_B.setFont(font2)
        self.nodo_B.setStyleSheet(u"background-color: rgb(128, 152, 180);")
        self.nodo_H = QRadioButton(self.page_2)
        self.nodo_H.setObjectName(u"nodo_H")
        self.nodo_H.setGeometry(QRect(40, 160, 100, 40))
        self.nodo_H.setFont(font2)
        self.nodo_H.setStyleSheet(u"background-color: rgb(128, 152, 180);")
        self.nodo_C = QRadioButton(self.page_2)
        self.nodo_C.setObjectName(u"nodo_C")
        self.nodo_C.setGeometry(QRect(310, 60, 100, 40))
        self.nodo_C.setFont(font2)
        self.nodo_C.setStyleSheet(u"background-color: rgb(128, 152, 180);")
        self.nodo_D = QRadioButton(self.page_2)
        self.nodo_D.setObjectName(u"nodo_D")
        self.nodo_D.setGeometry(QRect(40, 110, 100, 40))
        self.nodo_D.setFont(font2)
        self.nodo_D.setStyleSheet(u"background-color: rgb(128, 152, 180);")
        self.nodo_F = QRadioButton(self.page_2)
        self.nodo_F.setObjectName(u"nodo_F")
        self.nodo_F.setGeometry(QRect(310, 110, 100, 40))
        self.nodo_F.setFont(font2)
        self.nodo_F.setStyleSheet(u"background-color: rgb(124, 146, 174);")
        self.nodo_I = QRadioButton(self.page_2)
        self.nodo_I.setObjectName(u"nodo_I")
        self.nodo_I.setGeometry(QRect(310, 160, 100, 40))
        self.nodo_I.setFont(font2)
        self.nodo_I.setStyleSheet(u"background-color: rgb(124, 146, 174);")
        self.nodo_A = QRadioButton(self.page_2)
        self.nodo_A.setObjectName(u"nodo_A")
        self.nodo_A.setGeometry(QRect(40, 60, 100, 40))
        self.nodo_A.setFont(font2)
        self.nodo_A.setStyleSheet(u"background-color: rgb(128, 152, 180);")
        self.boton_inicio = QPushButton(self.page_2)
        self.boton_inicio.setObjectName(u"boton_inicio")
        self.boton_inicio.setGeometry(QRect(20, 250, 91, 41))
        self.boton_inicio.setAutoFillBackground(True)
        self.boton_inicio.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"font: 9pt \"Consolas\";")
        self.boton_fin = QPushButton(self.page_2)
        self.boton_fin.setObjectName(u"boton_fin")
        self.boton_fin.setGeometry(QRect(20, 300, 91, 41))
        self.boton_fin.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"font: 9pt \"Consolas\";")
        self.opc_inicio = QLineEdit(self.page_2)
        self.opc_inicio.setObjectName(u"opc_inicio")
        self.opc_inicio.setGeometry(QRect(120, 260, 113, 20))
        self.opc_inicio.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.opc_fin = QLineEdit(self.page_2)
        self.opc_fin.setObjectName(u"opc_fin")
        self.opc_fin.setGeometry(QRect(120, 310, 113, 20))
        self.opc_fin.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.clear = QPushButton(self.page_2)
        self.clear.setObjectName(u"clear")
        self.clear.setGeometry(QRect(290, 300, 121, 41))
        font3 = QFont()
        font3.setFamily(u"Consolas")
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        font3.setStrikeOut(False)
        self.clear.setFont(font3)
        self.clear.setStyleSheet(u"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));")
        self.confirmar_n = QPushButton(self.page_2)
        self.confirmar_n.setObjectName(u"confirmar_n")
        self.confirmar_n.setGeometry(QRect(290, 250, 121, 41))
        self.confirmar_n.setStyleSheet(u"background-color: rgb(0, 255, 0);\n"
"font: 75 italic 10pt \"Consolas\";\n"
"")
        self.mostrar_grafico = QPushButton(self.page_2)
        self.mostrar_grafico.setObjectName(u"mostrar_grafico")
        self.mostrar_grafico.setGeometry(QRect(10, 350, 121, 41))
        self.mostrar_grafico.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(87, 86, 86);\n"
"font: 9pt \"Consolas\";")
        self.back = QPushButton(self.page_2)
        self.back.setObjectName(u"back")
        self.back.setGeometry(QRect(150, 350, 121, 41))
        self.back.setStyleSheet(u"background-color: rgb(170, 170, 255);\n"
"font: 10pt \"Consolas\";")
        self.label_2 = QLabel(self.page_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 481, 401))
        self.label_2.setStyleSheet(u"border-image: url(:/robot/bender.png);")
        self.stackedWidget.addWidget(self.page_2)
        self.label_2.raise_()
        self.label_4.raise_()
        self.nodo_E.raise_()
        self.nodo_G.raise_()
        self.nodo_B.raise_()
        self.nodo_H.raise_()
        self.nodo_C.raise_()
        self.nodo_D.raise_()
        self.nodo_F.raise_()
        self.nodo_I.raise_()
        self.nodo_A.raise_()
        self.boton_inicio.raise_()
        self.boton_fin.raise_()
        self.opc_inicio.raise_()
        self.opc_fin.raise_()
        self.clear.raise_()
        self.confirmar_n.raise_()
        self.mostrar_grafico.raise_()
        self.back.raise_()
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_3 = QLabel(self.page_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 0, 241, 41))
        font4 = QFont()
        font4.setFamily(u"Consolas")
        font4.setPointSize(16)
        self.label_3.setFont(font4)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.irconfimov = QPushButton(self.page_3)
        self.irconfimov.setObjectName(u"irconfimov")
        self.irconfimov.setGeometry(QRect(250, 300, 141, 51))
        self.progreso = QTextBrowser(self.page_3)
        self.progreso.setObjectName(u"progreso")
        self.progreso.setGeometry(QRect(250, 40, 151, 111))
        self.camera = QLabel(self.page_3)
        self.camera.setObjectName(u"camera")
        self.camera.setGeometry(QRect(20, 50, 211, 181))
        self.progressBarnodo = QProgressBar(self.page_3)
        self.progressBarnodo.setObjectName(u"progressBarnodo")
        self.progressBarnodo.setGeometry(QRect(250, 180, 118, 23))
        self.progressBarnodo.setValue(24)
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(Dialog)

        self.stackedWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.entrar.setText(QCoreApplication.translate("Dialog", u"Entrar ", None))
        self.contrasena.setText("")
        self.usuario.setText(QCoreApplication.translate("Dialog", u"User", None))
        self.usuario_2.setText("")
        self.contra.setText(QCoreApplication.translate("Dialog", u"Contrase\u00f1a", None))
        self.titulo.setText(QCoreApplication.translate("Dialog", u"Sign ", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Menu principal", None))
        self.mover_r.setText(QCoreApplication.translate("Dialog", u"Mover", None))
        self.herramienta.setText(QCoreApplication.translate("Dialog", u"Herramientas", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Configurar de movimiento ", None))
        self.nodo_E.setText(QCoreApplication.translate("Dialog", u"E", None))
        self.nodo_G.setText(QCoreApplication.translate("Dialog", u"G", None))
        self.nodo_B.setText(QCoreApplication.translate("Dialog", u"B", None))
        self.nodo_H.setText(QCoreApplication.translate("Dialog", u"H", None))
        self.nodo_C.setText(QCoreApplication.translate("Dialog", u"C", None))
        self.nodo_D.setText(QCoreApplication.translate("Dialog", u"D", None))
        self.nodo_F.setText(QCoreApplication.translate("Dialog", u"F", None))
        self.nodo_I.setText(QCoreApplication.translate("Dialog", u"I", None))
        self.nodo_A.setText(QCoreApplication.translate("Dialog", u"A", None))
        self.boton_inicio.setText(QCoreApplication.translate("Dialog", u"Inicio", None))
        self.boton_fin.setText(QCoreApplication.translate("Dialog", u"Fin ", None))
        self.clear.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.confirmar_n.setText(QCoreApplication.translate("Dialog", u"Iniciar viaje", None))
        self.mostrar_grafico.setText(QCoreApplication.translate("Dialog", u"Mostrar grafico ", None))
        self.back.setText(QCoreApplication.translate("Dialog", u"Volver", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Viaje en curso", None))
        self.irconfimov.setText(QCoreApplication.translate("Dialog", u"Configurar  movimiento", None))
        self.camera.setText("")
    # retranslateUi

