# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RoC.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(500, 450)
        self.stackedWidget = QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 500, 450))
        self.stackedWidget.setStyleSheet(u"")
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.fondo_1 = QLabel(self.page_4)
        self.fondo_1.setObjectName(u"fondo_1")
        self.fondo_1.setGeometry(QRect(0, 0, 500, 450))
        self.fondo_1.setPixmap(QPixmap(u"fondos/1234.png"))
        self.fondo_1.setScaledContents(True)
        self.frame = QFrame(self.page_4)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(80, 90, 341, 251))
        self.frame.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(2)
        self.la_usuario = QLabel(self.frame)
        self.la_usuario.setObjectName(u"la_usuario")
        self.la_usuario.setGeometry(QRect(20, 90, 81, 31))
        self.la_usuario.setStyleSheet(u"font: 75 14pt \"Verdana\";")
        self.la_contrasena = QLabel(self.frame)
        self.la_contrasena.setObjectName(u"la_contrasena")
        self.la_contrasena.setGeometry(QRect(20, 150, 111, 41))
        self.la_contrasena.setStyleSheet(u"font: 75 14pt \"Verdana\";")
        self.usuario = QLineEdit(self.frame)
        self.usuario.setObjectName(u"usuario")
        self.usuario.setGeometry(QRect(170, 90, 151, 31))
        self.usuario.setEchoMode(QLineEdit.Normal)
        self.contrasena = QLineEdit(self.frame)
        self.contrasena.setObjectName(u"contrasena")
        self.contrasena.setGeometry(QRect(170, 150, 151, 31))
        self.contrasena.setEchoMode(QLineEdit.Password)
        self.entrar = QPushButton(self.frame)
        self.entrar.setObjectName(u"entrar")
        self.entrar.setGeometry(QRect(200, 200, 121, 31))
        self.entrar.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.141243 rgba(18, 102, 139, 255), stop:1 rgba(255, 255, 255, 255));")
        self.la_titulo = QLabel(self.frame)
        self.la_titulo.setObjectName(u"la_titulo")
        self.la_titulo.setGeometry(QRect(130, 20, 71, 51))
        self.la_titulo.setStyleSheet(u"font: 75 italic 28pt \"Artifakt Element\";")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.titulo_p2 = QLabel(self.page)
        self.titulo_p2.setObjectName(u"titulo_p2")
        self.titulo_p2.setGeometry(QRect(125, 20, 250, 71))
        self.titulo_p2.setStyleSheet(u"font: 75 italic 28pt \"Artifakt Element\";")
        self.mover_r = QPushButton(self.page)
        self.mover_r.setObjectName(u"mover_r")
        self.mover_r.setGeometry(QRect(270, 220, 161, 101))
        self.mover_r.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.herramienta = QPushButton(self.page)
        self.herramienta.setObjectName(u"herramienta")
        self.herramienta.setGeometry(QRect(70, 220, 161, 101))
        self.herramienta.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.fondo_2 = QLabel(self.page)
        self.fondo_2.setObjectName(u"fondo_2")
        self.fondo_2.setGeometry(QRect(0, 0, 500, 450))
        self.fondo_2.setPixmap(QPixmap(u"fondos/123.jpg"))
        self.fondo_2.setScaledContents(True)
        self.stackedWidget.addWidget(self.page)
        self.fondo_2.raise_()
        self.titulo_p2.raise_()
        self.mover_r.raise_()
        self.herramienta.raise_()
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.titulo_p3 = QLabel(self.page_2)
        self.titulo_p3.setObjectName(u"titulo_p3")
        self.titulo_p3.setGeometry(QRect(100, 0, 311, 61))
        font = QFont()
        font.setFamily(u"Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_p3.setFont(font)
        self.titulo_p3.setStyleSheet(u"")
        self.nodo_E = QRadioButton(self.page_2)
        self.nodo_E.setObjectName(u"nodo_E")
        self.nodo_E.setGeometry(QRect(200, 110, 100, 40))
        font1 = QFont()
        font1.setFamily(u"Consolas")
        font1.setPointSize(10)
        self.nodo_E.setFont(font1)
        self.nodo_E.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.nodo_G = QRadioButton(self.page_2)
        self.nodo_G.setObjectName(u"nodo_G")
        self.nodo_G.setGeometry(QRect(200, 160, 100, 40))
        self.nodo_G.setFont(font1)
        self.nodo_G.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.nodo_B = QRadioButton(self.page_2)
        self.nodo_B.setObjectName(u"nodo_B")
        self.nodo_B.setGeometry(QRect(200, 60, 100, 40))
        self.nodo_B.setFont(font1)
        self.nodo_B.setStyleSheet(u"background-color: rgb(255, 255, 255,220);\n"
"")
        self.nodo_H = QRadioButton(self.page_2)
        self.nodo_H.setObjectName(u"nodo_H")
        self.nodo_H.setGeometry(QRect(60, 160, 100, 40))
        self.nodo_H.setFont(font1)
        self.nodo_H.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.nodo_C = QRadioButton(self.page_2)
        self.nodo_C.setObjectName(u"nodo_C")
        self.nodo_C.setGeometry(QRect(330, 60, 100, 40))
        self.nodo_C.setFont(font1)
        self.nodo_C.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.nodo_D = QRadioButton(self.page_2)
        self.nodo_D.setObjectName(u"nodo_D")
        self.nodo_D.setGeometry(QRect(60, 110, 100, 40))
        self.nodo_D.setFont(font1)
        self.nodo_D.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.nodo_F = QRadioButton(self.page_2)
        self.nodo_F.setObjectName(u"nodo_F")
        self.nodo_F.setGeometry(QRect(330, 110, 100, 40))
        self.nodo_F.setFont(font1)
        self.nodo_F.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.nodo_I = QRadioButton(self.page_2)
        self.nodo_I.setObjectName(u"nodo_I")
        self.nodo_I.setGeometry(QRect(330, 160, 100, 40))
        self.nodo_I.setFont(font1)
        self.nodo_I.setStyleSheet(u"background-color: rgb(255, 255, 255,220);\n"
"")
        self.nodo_A = QRadioButton(self.page_2)
        self.nodo_A.setObjectName(u"nodo_A")
        self.nodo_A.setGeometry(QRect(60, 60, 100, 40))
        self.nodo_A.setFont(font1)
        self.nodo_A.setStyleSheet(u"background-color: rgb(255, 255, 255,220);")
        self.boton_inicio = QPushButton(self.page_2)
        self.boton_inicio.setObjectName(u"boton_inicio")
        self.boton_inicio.setGeometry(QRect(60, 250, 91, 41))
        self.boton_inicio.setAutoFillBackground(False)
        self.boton_inicio.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"font: 9pt \"Consolas\";")
        self.boton_fin = QPushButton(self.page_2)
        self.boton_fin.setObjectName(u"boton_fin")
        self.boton_fin.setGeometry(QRect(60, 300, 91, 41))
        self.boton_fin.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"font: 9pt \"Consolas\";")
        self.opc_inicio = QLineEdit(self.page_2)
        self.opc_inicio.setObjectName(u"opc_inicio")
        self.opc_inicio.setGeometry(QRect(160, 260, 113, 20))
        self.opc_inicio.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.opc_fin = QLineEdit(self.page_2)
        self.opc_fin.setObjectName(u"opc_fin")
        self.opc_fin.setGeometry(QRect(160, 310, 113, 20))
        self.opc_fin.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.btn_clear = QPushButton(self.page_2)
        self.btn_clear.setObjectName(u"btn_clear")
        self.btn_clear.setGeometry(QRect(330, 290, 131, 51))
        font2 = QFont()
        font2.setFamily(u"Consolas")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        font2.setStrikeOut(False)
        self.btn_clear.setFont(font2)
        self.btn_clear.setStyleSheet(u"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));")
        self.confirmar_n = QPushButton(self.page_2)
        self.confirmar_n.setObjectName(u"confirmar_n")
        self.confirmar_n.setGeometry(QRect(330, 370, 121, 51))
        self.confirmar_n.setStyleSheet(u"background-color: rgb(0, 255, 0);\n"
"font: 75 italic 10pt \"Consolas\";\n"
"")
        self.mostrar_grafico = QPushButton(self.page_2)
        self.mostrar_grafico.setObjectName(u"mostrar_grafico")
        self.mostrar_grafico.setGeometry(QRect(60, 370, 111, 51))
        self.mostrar_grafico.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(87, 86, 86);\n"
"font: 9pt \"Consolas\";")
        self.back = QPushButton(self.page_2)
        self.back.setObjectName(u"back")
        self.back.setGeometry(QRect(190, 370, 111, 51))
        self.back.setStyleSheet(u"background-color: rgb(170, 170, 255);\n"
"font: 10pt \"Consolas\";")
        self.fondo_3 = QLabel(self.page_2)
        self.fondo_3.setObjectName(u"fondo_3")
        self.fondo_3.setGeometry(QRect(0, 0, 500, 450))
        self.fondo_3.setPixmap(QPixmap(u"fondos/1234.jpg"))
        self.fondo_3.setScaledContents(True)
        self.stackedWidget.addWidget(self.page_2)
        self.fondo_3.raise_()
        self.titulo_p3.raise_()
        self.nodo_E.raise_()
        self.nodo_G.raise_()
        self.nodo_B.raise_()
        self.nodo_H.raise_()
        self.nodo_C.raise_()
        self.nodo_D.raise_()
        self.nodo_F.raise_()
        self.nodo_I.raise_()
        self.nodo_A.raise_()
        self.boton_inicio.raise_()
        self.boton_fin.raise_()
        self.opc_inicio.raise_()
        self.opc_fin.raise_()
        self.btn_clear.raise_()
        self.confirmar_n.raise_()
        self.mostrar_grafico.raise_()
        self.back.raise_()
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.titulo_p4 = QLabel(self.page_3)
        self.titulo_p4.setObjectName(u"titulo_p4")
        self.titulo_p4.setGeometry(QRect(120, 0, 241, 41))
        font3 = QFont()
        font3.setFamily(u"MS Shell Dlg 2")
        font3.setPointSize(24)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setWeight(50)
        self.titulo_p4.setFont(font3)
        self.titulo_p4.setStyleSheet(u"font: 24pt \"MS Shell Dlg 2\";")
        self.titulo_p4.setAlignment(Qt.AlignCenter)
        self.irconfimov = QPushButton(self.page_3)
        self.irconfimov.setObjectName(u"irconfimov")
        self.irconfimov.setGeometry(QRect(280, 330, 181, 51))
        self.irconfimov.setStyleSheet(u"background-color: rgb(255, 85, 0);\n"
"font: 75 10pt \"Consolas\";")
        self.show = QPushButton(self.page_3)
        self.show.setObjectName(u"show")
        self.show.setGeometry(QRect(50, 330, 111, 51))
        self.show.setStyleSheet(u"background-color: rgb(255, 255, 127);\n"
"font: 75 10pt \"Consolas\";")
        self.imagen = QLabel(self.page_3)
        self.imagen.setObjectName(u"imagen")
        self.imagen.setGeometry(QRect(90, 40, 300, 200))
        self.imagen.setFrameShape(QFrame.Box)
        self.progresaBar = QProgressBar(self.page_3)
        self.progresaBar.setObjectName(u"progresaBar")
        self.progresaBar.setGeometry(QRect(320, 250, 118, 23))
        self.progresaBar.setValue(24)
        self.fondo_4 = QLabel(self.page_3)
        self.fondo_4.setObjectName(u"fondo_4")
        self.fondo_4.setGeometry(QRect(0, 0, 500, 450))
        self.fondo_4.setPixmap(QPixmap(u"fondos/cmatrix.png"))
        self.fondo_4.setScaledContents(True)
        self.stop_record = QPushButton(self.page_3)
        self.stop_record.setObjectName(u"stop_record")
        self.stop_record.setGeometry(QRect(180, 320, 75, 61))
        self.line_progreso = QLineEdit(self.page_3)
        self.line_progreso.setObjectName(u"line_progreso")
        self.line_progreso.setGeometry(QRect(80, 250, 191, 41))
        self.stackedWidget.addWidget(self.page_3)
        self.fondo_4.raise_()
        self.titulo_p4.raise_()
        self.irconfimov.raise_()
        self.show.raise_()
        self.progresaBar.raise_()
        self.imagen.raise_()
        self.stop_record.raise_()
        self.line_progreso.raise_()

        self.retranslateUi(Dialog)

        self.stackedWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.fondo_1.setText("")
        self.la_usuario.setText(QCoreApplication.translate("Dialog", u"Usuario", None))
        self.la_contrasena.setText(QCoreApplication.translate("Dialog", u"Contrase\u00f1a", None))
        self.usuario.setText("")
        self.contrasena.setText("")
        self.entrar.setText(QCoreApplication.translate("Dialog", u"Acceder", None))
        self.la_titulo.setText(QCoreApplication.translate("Dialog", u"RoC", None))
        self.titulo_p2.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Menu principal</span></p></body></html>", None))
        self.mover_r.setText(QCoreApplication.translate("Dialog", u"Mover", None))
        self.herramienta.setText(QCoreApplication.translate("Dialog", u"Herramientas", None))
        self.fondo_2.setText("")
        self.titulo_p3.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Configurar de movimiento </span></p></body></html>", None))
        self.nodo_E.setText(QCoreApplication.translate("Dialog", u"E", None))
        self.nodo_G.setText(QCoreApplication.translate("Dialog", u"G", None))
        self.nodo_B.setText(QCoreApplication.translate("Dialog", u"B", None))
        self.nodo_H.setText(QCoreApplication.translate("Dialog", u"H", None))
        self.nodo_C.setText(QCoreApplication.translate("Dialog", u"C", None))
        self.nodo_D.setText(QCoreApplication.translate("Dialog", u"D", None))
        self.nodo_F.setText(QCoreApplication.translate("Dialog", u"F", None))
        self.nodo_I.setText(QCoreApplication.translate("Dialog", u"I", None))
        self.nodo_A.setText(QCoreApplication.translate("Dialog", u"A", None))
        self.boton_inicio.setText(QCoreApplication.translate("Dialog", u"Inicio", None))
        self.boton_fin.setText(QCoreApplication.translate("Dialog", u"Fin ", None))
        self.btn_clear.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.confirmar_n.setText(QCoreApplication.translate("Dialog", u"Iniciar viaje", None))
        self.mostrar_grafico.setText(QCoreApplication.translate("Dialog", u"Mostrar grafico ", None))
        self.back.setText(QCoreApplication.translate("Dialog", u"Volver", None))
        self.fondo_3.setText("")
        self.titulo_p4.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Viaje en curso</span></p></body></html>", None))
        self.irconfimov.setText(QCoreApplication.translate("Dialog", u"Configurar  movimiento", None))
        self.show.setText(QCoreApplication.translate("Dialog", u"show", None))
        self.imagen.setText("")
        self.fondo_4.setText("")
        self.stop_record.setText(QCoreApplication.translate("Dialog", u"Stop", None))
    # retranslateUi

